### PR TITLE
Privacy Policy 

### PR DESCRIPTION
**Pull request by princekelly1**
A privacy policy statement for the QKSMS application.
A users once asked about this on reddit and he got no reply click [here](https://www.reddit.com/r/QKSMS/comments/5upbck/privacy_policy/) to see the users statement.
review ,let me know if there should be any addition to be made, or kindly merge to the project as part of my way in contributing to QKSMS

### CODE REVIEW

**Comment by realmain** [comment]
> We do allow third-party companies to collect certain non-personal information for the purposes of behavioral advertising. These companies may utilize cookies, pixels or other technologies to collect and use non-personally identifiable information (e.g., hashed data, click stream information, browser type, time and date, subject of advertisements clicked or scrolled over) during your use of the app and other web sites in order to provide advertisements about goods and services likely to be of greater interest to you. To learn more about this behavioral advertising practice or to opt-out of this type of advertising, you can visit the websites of the Digital Advertising Alliance at www.aboutads.info and Networking Advertising Initiative at www.networkadvertising.org/choices.

Is this really a thing in QKSMS?

**Comment by princekelly1** [comment]
Must SMS application, do. 
I would edit it out and make the final pull request.

**Comment by sm4rk0** [comment]
Only privacy-sensitive thing I found looking at the code is Mixpanel and Amplitude analytics data sent when user taps "Rate" or "Dismiss" when asked to rate the app, or when they tap "Upgrade" button. That's only for the [Google Play Store version](https://play.google.com/store/apps/details?id=com.moez.QKSMS). [F-Droid version](https://f-droid.org/packages/com.moez.QKSMS/) is "clean".

**Comment by princekelly1** [comment]
ok

**Comment by princekelly1** [comment]
I have made all necessary changes, please check. Thank you

**Comment by chadouming** [comment]
1. Should tidy up your stuff. No need for 4 commits to create file.
2. Is that really a policy for this app or a generic one found on another SMS app ?
3. You should name the pull request according to your changes and not "Princekelly1 patch 2" which basically mean nothing to anyone else but you.

**Comment by princekelly1** [comment]
Seems it didn't reflect, I would check it and get back to you

**Comment by princekelly1** [comment]
I would make the noted change, @chadouming

**Comment by realmain** [comment]
You should just delete the first 3 commits so that they don't show up in this pull request. It makes it look really messy.

**Comment by princekelly1** [comment]
closing this for a new pull now.

**Comment by moezbhatti** [comment]
@realmain nope, QKSMS doesn't send any info to advertisers. This looks like a generic policy that was pulled from the internet and is not related to QKSMS

@sm4rk0's comment explaining the data that *is* collected by QKSMS is accurate

**Pull request closed without merging**
