### PR TITLE
Create QKSMS FAQ

### PR DESCRIPTION
**Pull request by tnsmith12**
Hi, I have being using your application for sometime and i love to make a contribution to it, by adding the FAQ section to help users understand how to use the application.
they can get their questions answered easily
You can merge it, if satisfied with my write up. Thank you.

### CODE REVIEW

**Comment by princekelly1** [comment]
Tnsmith12 please review the FAQ, and make corrections.

**Comment by princekelly1** [comment]
I guess, it would make the application look different to others. My
thoughts

**Comment by princekelly1** [comment]
And it gives copy writers a chance to contribute, to open source projects.

On Apr 25, 2018 5:25 PM, "Micheal Adelabu" <adelabu93@gmail.com> wrote:

I guess, it would make the application look different to others. My
thoughts

**Comment by realmain** [comment]
> And it gives copy writers a chance to contribute, to open source projects.

I don't understand how a FAQ about a simple SMS app give people a chance to contribute. They can just go to the GitHub and do it?

**Comment by tnsmith12** [comment]
I'm sorry for that, I'll review that and adjust the grammar,
Thanks.

**Comment by princekelly1** [comment]
When they can't write codes, they can write words? About things relating to
the application.

**Comment by moezbhatti** [comment]
I appreciate the effort here, but as others have mentioned, this isn't something that would be particularly helpful for the audience of the app.

In the future I may add something inside of the app to help users configure their MMS settings or other things like that, but for now I'll be closing this.

**Pull request closed without merging**
