### PR TITLE
Trim whitespace in message summary

### LINKED ISSUE #1169: Trim leading whitespace and remove line breaks in message previews
### DESCRIPTION
Messages with leading whitespace (e.g. newline) show only an ellipsis for the message preview in the messages list

### STEPS
1. send a message to yourself where the first line is `\n`

### EXPECTED
I would want to see as much of the message as will fit on a single line with leading whitespace and linebreaks removed.

The algorithm could be something like:

```kotlin
val previewText = messageText.replace("\n", " ").trim()
```

### OBSERVATIONS
Since there is no visible characters in the first line of the message, the preview is simply an ellipsis `...`

### PR DESCRIPTION
**Pull request by joshfriend**
fixes #1169

### CODE REVIEW

**Comment by moezbhatti** [comment]
This will trim the whitespace between lines between text in a notification as well

Perhaps this should happen when binding the summary in the ConversationAdapter

**Comment by joshfriend** [comment]
Unless android studio is lying to me, the only place that `getSummary()` is used is when building the sms notification (`NotificationManagerImpl.kt`) and when computing a conversation's `snippet` property. When I tested this, the text of the message was compacted for visibility where I think you would want it (notification, conversation list and search results), but showed the full text for total accuracy when inside the conversation itself.

**Comment by joshfriend** [comment]
To your [comment here](https://github.com/moezbhatti/qksms/issues/1169#issuecomment-395605918), I agree with your desire to show the exact message text when viewing the conversation detail. I think it should be compacted in all other situations, which I believe I have implemented here.

**Comment by moezbhatti** [comment]
Ah! I wasn't very clear with my comment there - I meant to imply that I don't think that it should be compacted in the notifications (or at least, it should be compacted differently)

The reason being is that notifications are able to show multiple lines of text, so it would be unnecessary to trim the spaces between the lines here (though it would make sense to trim space before and after)

Also, something to note is that when a conversation is unread, it will show multiple lines of text in the snippet, so this is another case where it would be unnecessary to trim the spaces between the lines

With this in mind I think there's two possible solutions

### Solution 1
This is in the case that we don't feel that it is necessary to trim space between lines when the conversation is read (so, it will not show any text that was written after a line break)

- Trim around lines in `Message.getSummary()`


### Solution 2
This solution is preferred if we want to trim between lines in the summary for read messages

- Trim between lines for read messages in `ConversationAdapter`
- Trim around lines for unread messages in `ConversationAdapter`
- Trim around lines in `NotificationManagerImpl`


Personally, I'm leaning towards solution 1. It's cleaner, and I don't think it's necessary to trim between lines for read messages because android will automatically handle this case by adding a `...` to indicate that there's more text

**Pull request closed without merging**
