### PR TITLE
Does not scroll to bottom of current conversation if no new SMS are r…

### PR DESCRIPTION
**Pull request by StephaneBausseron**
…eceived in this conversation

Workaround for issue #587

### CODE REVIEW

**Comment by StephaneBausseron** [comment]
Just push an improved version of the fix. Now a compare the last message ID of conversation before and after onChanged event. If latest message changed, application scroll to bottom.

**Comment by moezbhatti** [comment]
Hey @StephaneBausseron, sorry for taking so long to review this! The last few weeks have just been very busy. In the future, I'll try to make sure I'm reviewing your PRs within a day or two

I really appreciate all of the commits you've been making

Tested this change, and it works great by the way 👍 

My only suggestion would be, instead of storing `mLastMessage` and calling `mLastMessage.getMessageId()`, maybe we should just store `long mLastMessageId`

**Comment by StephaneBausseron** [comment]
No problem. It's an open source project ;).
Your suggestion sounds good for me. Fixed. Branch rebased on master + removing another mLastMessageId which is unused (to prevent from confusing with the new mLastMessageId variable).

**Comment by moezbhatti** [comment]
Thanks, glad you understand 😄 
Looks good, now. Merging

**Pull request merged**
