### PR TITLE
Update README.md build status

### PR DESCRIPTION
**Pull request by MyNameIsCosmo**
branch=master -> branch=qksms3

### CODE REVIEW

**Comment by moezbhatti** [comment]
Thanks! I'll just need to remember to change this back to master once the release is ready, haha

**Comment by MyNameIsCosmo** [comment]
Look into pre-commit hooks:
https://stackoverflow.com/questions/18673694/referencing-current-branch-in-github-readme-md/35368808#35368808

**Comment by MyNameIsCosmo** [comment]
It may also be worthwhile to set up a service like [Codacy](https://codacy.com) to do automated code reviews and analytics.

Example: https://www.codacy.com/app/MyNameIsCosmo/qksms/dashboard?bid=6283780

**Comment by moezbhatti** [comment]
@MyNameIsCosmo this is really cool, thanks for the link

**Pull request merged**
